### ISSUE TITLE
gem cert is expired on 2017-04-24 02:51:23 UTC

### ISSUE THREAD

**Issue by TangRufus** [bkuhlmann/gemsmith#3]
```bash
$ gem cert --add <(curl --location --silent https://www.alchemists.io/gem-public.pem)
Added '/CN=brooke/DC=alchemists/DC=io'

$ gem install gemsmith --trust-policy MediumSecurity
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=accounts_rubygems/DC=thekompanee/DC=com not valid after 2017-04-24 02:51:23 UTC
```

**Comment by bkuhlmann** [comment]
This does not happen on Ruby `2.4.1` with the latest version of Gemsmith. It's possible that you might be trying to install an older version of Gemsmith (which would be outdated in that case). What version of Ruby are you trying to install Gemsmith on?

**Comment by bkuhlmann** [comment]
Could you also provide environment information as well? Example:

```
gem -v
2.6.13

ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
```

**Comment by TangRufus** [comment]
here you go:

macOS 10.12.6

```bash
gem -v
2.6.13

ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]

rbenv -v
rbenv 1.1.1

gem cert --add <(curl --location --silent https://www.alchemists.io/gem-public.pem)
Added '/CN=brooke/DC=alchemists/DC=io'

gem cert --list
/CN=brooke/DC=alchemists/DC=io

gem install gemsmith --trust-policy MediumSecurity
ERROR:  While executing gem ... (Gem::Security::Exception)
    certificate /CN=accounts_rubygems/DC=thekompanee/DC=com not valid after 2017-04-24 02:51:23 UTC
```

**Comment by TangRufus** [comment]
opss.....

After a closer look the expired certificate isn't from gemsmith.

Sorry for the trouble.

**Comment by bkuhlmann** [comment]
Thanks. Yeah, saw that too. I went through the Gemsmith gem dependencies but there isn't a dependency on `thekompanee` that I can detect. It looks to be a different gem unrelated to the install of Gemsmith. I'm going to close this as there isn't anything I need to fix on my side. If you need a workaround, you might be fine using: `gem install gemsmith --trust-policy LowSecurity`.

**Comment by TangRufus** [comment]
I guess jfelchner/ruby-progressbar is the culprit. Thanks!

https://github.com/jfelchner/ruby-progressbar/issues/135

**Comment by bkuhlmann** [comment]
Ha, nice, good find.

**Comment by jfelchner** [comment]
@TangRufus @bkuhlmann I'm releasing a new version with a fixed certificate now.  Thanks for the patience.  OSS is hard. :)

**Comment by jfelchner** [comment]
All, https://github.com/jfelchner/ruby-progressbar/commit/d4657abde6e477767e9156053e7d0065cab3b0ef fixes this issue and is released as of [1.8.3](https://github.com/jfelchner/ruby-progressbar/tree/releases/v1.8.3).  Again, sorry for the issue and the delay of the fix.

**Comment by jfelchner** [comment]
For the record Rubygems requires a new cert every year, so you'll have to trust the new public cert.

**Comment by jfelchner** [comment]
I also now have a scheduled todo item which will remind me to rotate these next year before they expire 😉

**Comment by bkuhlmann** [comment]
@jfelchner Awesome, thanks for taking care of this.

**Comment by jonknapp** [comment]
@jfelchner hi Jeff, it looks like the cert may have expired again.

**Comment by jonknapp** [comment]
Nevermind, please ignore. I needed to run the following locally:

```
gem cert --add <(curl -Ls https://raw.githubusercontent.com/jfelchner/ruby-progressbar/master/certs/jfelchner.pem)
```
