### ISSUE TITLE
Add YARD support.

### ISSUE THREAD

**Issue by baweaver** [bkuhlmann/gemsmith#5]
What would be your thoughts on integrating YARDoc and steps to build a github pages site automatically from the output?

I'd be willing to write some of it up, just want to make sure it'd be of interest before I put code to commit.

**Comment by bkuhlmann** [comment]
I suppose it depends on how hard it is to integrate and maintain (more so the latter). What is the need for adding documentation? Why is it necessary versus focusing on good self-describing code?

**Comment by baweaver** [comment]
YARDoc is mostly a pre-comment addition that describes expected input, output, examples, notes, deprecations, and other meta concerns that tend to transcend merely the code.

For instance, I write a lot of documentation explaining pattern match inline here: https://github.com/baweaver/qo/blob/master/lib/qo/matchers/pattern_match.rb

...which ends up translating to this with YARDoc:
https://baweaver.github.io/qo/Qo/Matchers/PatternMatch.html

Noted I could probably do for a more detailed explanation, but the general idea is that it gives you a more formal structure for API docs which are especially useful for gems.

**Comment by bkuhlmann** [comment]
One thing I've always liked about the Ruby language is that you can be expressive and concise at the same time without the overhead of complex documentation. I also like being able to read through code without having to filter through all of the metadata (documentation in this case) noise. Perhaps, this is influence from the early days of Ruby having written Ruby code for more than a decade now. :)

Now that I write a lot more [Elm](http://elm-lang.org) code, I definitely see the benefit of explaining inputs and outputs to methods better. Sadly, Ruby is harder to maintain as there is no compiler, like Elm has, which will point out you have a typo or misrepresented the type of an input/output to your method(s). Again, my hesitation to adding this kind of overhead to Ruby as the documentation quality is only as good as how disciplined the author is.

All of that said, I'm fine with proceeding. It will add additional maintenance but the payoff will be useful to others new to learning how gems work such as this one.

There will be many ramifications from doing this work, though:

- This gem will need to be updated to use Yard (I can start making a pass through this).
- All of my other gems will have to be updated to use Yard (this falls on me).
- Yard has a lot of customization options which will need to be investigated. It might require surfacing these settings as part of the Gemsmith global configuration.
- It might be worthwhile to consider adding [Inch](https://inch-ci.org) badge support.
- This will require modifications to [Reek](https://github.com/troessner/reek) and [Rubocop](https://github.com/bbatsov/rubocop) settings a both of these don't require documentation but will need to be re-enabled once Yard support is added.
- There are probably other aspects to this work that will require consideration but we can tackle them as we go.

Do you have an idea of how you want to approach this work? We'll definitely need to break this down into smaller chunks of work.

**Comment by bkuhlmann** [comment]
Closing this due to lack of feedback/support. I am definitely considering this for future releases but acknowledge that this is going to take some effort to do right. I am definitely giving this more thought moving forward. Thanks!
