### ISSUE TITLE
Errors with gemsmith --generate

### ISSUE THREAD

**Issue by tleish** [bkuhlmann/gemsmith#8]
## Overview
I'm getting an errors when trying to generate a new gem from scratch.  Is this expected?  I do not see these same errors when watching the demo video.

```
         ... 
         run  bundle exec rubocop --auto-correct example > /dev/null from "."
cannot load such file -- rubocop-performance
```

```
         ...
         run  bundle install from "."
You have one or more invalid gemspecs that need to be fixed.
The gemspec at example/example.gemspec is not valid. Please fix this gemspec.
The validation error was 'metadata['source_code_uri'] has invalid link: ""'
```

## Steps to Recreate
```
$ gemsmith --generate example                                                                                                                                                                            
        info  Generating gem...
      create  example/bin/setup
      create  example/Gemfile
      create  example/example.gemspec
      create  example/lib/example.rb
      create  example/lib/example/identity.rb
       chmod  example/bin/setup
      create  example/README.md
      create  example/CONTRIBUTING.md
      create  example/CODE_OF_CONDUCT.md
      create  example/LICENSE.md
      create  example/CHANGES.md
      create  example/Rakefile
      append  example/Rakefile
      append  example/Rakefile
      create  example/.ruby-version
        gsub  example/Rakefile
        gsub  example/Rakefile
      create  example/spec/spec_helper.rb
      create  example/spec/support/shared_contexts/temp_dir.rb
        gsub  example/Rakefile
        gsub  example/Rakefile
        gsub  example/Rakefile
        gsub  example/Rakefile
        gsub  example/Rakefile
      create  example/.reek.yml
        gsub  example/Rakefile
        gsub  example/Rakefile
      create  example/.rubocop.yml
         run  bundle exec rubocop --auto-correct example > /dev/null from "."
cannot load such file -- rubocop-performance
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/config_loader_resolver.rb:15:in `require'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/config_loader_resolver.rb:11:in `each'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/config_loader.rb:45:in `load_file'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/config_loader_resolver.rb:142:in `block in base_configs'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/config_loader_resolver.rb:141:in `map'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/config_loader_resolver.rb:141:in `base_configs'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/config_loader_resolver.rb:22:in `resolve_inheritance'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/config_loader.rb:50:in `load_file'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/config_loader.rb:86:in `configuration_from_file'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/config_store.rb:44:in `for'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/target_finder.rb:112:in `excluded_dirs'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/target_finder.rb:90:in `find_files'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/target_finder.rb:60:in `target_files_in_dir'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/target_finder.rb:37:in `block in find'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/target_finder.rb:35:in `each'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/target_finder.rb:35:in `find'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:64:in `find_target_files'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/runner.rb:34:in `run'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cli.rb:210:in `execute_runner'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cli.rb:80:in `execute_runners'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/lib/rubocop/cli.rb:51:in `run'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/exe/rubocop:13:in `block in <top (required)>'
ruby/2.6.3/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/rubocop-0.74.0/exe/rubocop:12:in `<top (required)>'
ruby/2.6.3/bin/rubocop:23:in `load'
ruby/2.6.3/bin/rubocop:23:in `<top (required)>'
ruby/2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `load'
ruby/2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:74:in `kernel_load'
ruby/2.6.3/lib/ruby/2.6.0/bundler/cli/exec.rb:28:in `run'
ruby/2.6.3/lib/ruby/2.6.0/bundler/cli.rb:463:in `exec'
ruby/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
ruby/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
ruby/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
ruby/2.6.3/lib/ruby/2.6.0/bundler/cli.rb:27:in `dispatch'
ruby/2.6.3/lib/ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
ruby/2.6.3/lib/ruby/2.6.0/bundler/cli.rb:18:in `start'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:30:in `block in <top (required)>'
ruby/2.6.3/lib/ruby/2.6.0/bundler/friendly_errors.rb:124:in `with_friendly_errors'
ruby/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/exe/bundle:22:in `<top (required)>'
ruby/2.6.3/bin/bundle:23:in `load'
ruby/2.6.3/bin/bundle:23:in `<main>'
      create  example/Guardfile
        info  Installing gem dependencies...
         run  bundle install from "."
You have one or more invalid gemspecs that need to be fixed.
The gemspec at example/example.gemspec is not valid. Please fix this gemspec.
The validation error was 'metadata['source_code_uri'] has invalid link: ""'
      create  example/.github/ISSUE_TEMPLATE.md
      create  example/.github/PULL_REQUEST_TEMPLATE.md
      create  example/.gitignore
        info  Gem generation finished.
```
## Environment
- MacOS 10.14.6
- Ruby 2.6.3p62
- gemsmith 13.7.1

**Comment by bkuhlmann** [comment]
Hey @tleish, thanks for the feedback. I'm not able to reproduce locally, which is odd, but also makes me think it might be a gem dependency issue. What do you get when you run the following:

``` bash
gem list | grep rubocop
```

Here is what I see:

``` bash
rubocop (0.74.0)
rubocop-performance (1.4.1)
rubocop-rspec (1.35.0)
```

If you were to install `rubocop-performance` prior to generating a gem, does that help?

Also, do you have a global Rubocop configuration? If so what does it look like? I ask because I've seen some odd situations with global Rubocop configurations. You should be able to find one in either of these locations (if you have one at all):

- `$HOME/.config/rubocop/config.yml`
- `$HOME/.rubocop.yml`

**Comment by tleish** [comment]
Hi @bkuhlmann,

```shell
gem list | grep rubocop   

rubocop (0.74.0)
rubocop-performance (1.4.1)
rubocop-rspec (1.35.0)
```

I do have a global `.rubocop.yml`, but I temporarily removed the file based on your feedback and still experience the same error.

Any other suggestions?

**Comment by bkuhlmann** [comment]
@tleish until I can find a solution (and recreate locally), this might work as a temporary workaround. Do the following:

0. Run `gemsmith --open gemsmith`
0. Once in your editor, open this file (using a relative path here): `lib/gemsmith/templates/%gem_name%/.rubocop.yml.tt`.
0. Make sure to delete Line 3. It'll look like this: "  - https://raw.githubusercontent.com/bkuhlmann/code_quality/4.1.0/configurations/rubocop/performance.yml"
0. Save and exit.
0. Now run: `gemsmith --generate example`. This will generate a gem with Rubocop support minus the Performance checks. Alternatively, you could skip all of the steps above and just run `gemsmith --generate example --no-rubocop` but you wouldn't have any RSpec support at all in that case. :wink:



Once I have a patch ready for you, you can either upgrade to the new Gemsmith version or use `gem pristine gemsmith` to revert the changes above.

By the way, I'm not sure this is a Gemsmith issue...it might also be an issue with how Rubocop has split up performance, RSpec, and Rails into separate gems and this is an unfortunate side-effect.

**Comment by tleish** [comment]
Hi @bkuhlmann,

I figured out the issue.  In the directory I was running the gemsmith, I ran the following:

```shell
$ bundle list | grep rubocop
  * rubocop (0.74.0)
```

This surprised me for 2 reasons:
1. There's no Gemfile in the directory I am running the command from, so why did this work.
2. Since it did work, what gemset is it using to determine only use rubocop.

I remembered I had a `$HOME/Gemfile`.  This file has `rubocop`, but not `rubocop-performance`.  The `run  bundle exec rubocop --auto-correct example > /dev/null from "."` was picking up and using this Gemfile for the bundle environment.  Possible options are add `rubocop-performance` and `rubocop-rspec` to `$HOME/Gemfile` or remove `$HOME/Gemfile`.  With either option, I now see:

```
gemsmith --generate example
        info  Generating gem...
      create  example/bin/setup
      create  example/Gemfile
      create  example/example.gemspec
      create  example/lib/example.rb
      create  example/lib/example/identity.rb
       chmod  example/bin/setup
      create  example/README.md
      create  example/CONTRIBUTING.md
      create  example/CODE_OF_CONDUCT.md
      create  example/LICENSE.md
      create  example/CHANGES.md
      create  example/Rakefile
      append  example/Rakefile
      append  example/Rakefile
      create  example/.ruby-version
        gsub  example/Rakefile
        gsub  example/Rakefile
      create  example/spec/spec_helper.rb
      create  example/spec/support/shared_contexts/temp_dir.rb
        gsub  example/Rakefile
        gsub  example/Rakefile
        gsub  example/Rakefile
        gsub  example/Rakefile
        gsub  example/Rakefile
      create  example/.reek.yml
        gsub  example/Rakefile
        gsub  example/Rakefile
      create  example/.rubocop.yml
         run  bundle exec rubocop --auto-correct example > /dev/null from "."
      create  example/Guardfile
        info  Installing gem dependencies...
         run  bundle install from "."
You have one or more invalid gemspecs that need to be fixed.
The gemspec at example/example.gemspec is not valid. Please fix this gemspec.
The validation error was 'metadata['source_code_uri'] has invalid link: ""'
      create  example/.github/ISSUE_TEMPLATE.md
      create  example/.github/PULL_REQUEST_TEMPLATE.md
      create  example/.gitignore
        info  Gem generation finished.
```

I assume the `invalid gemspecs...` since it would have to read my brain to fill in this info?

**Comment by bkuhlmann** [comment]
@tleish, wow, I've never heard of a setup like this before...but nice find. :wink:

By the way, why do you have a global Gemfile (i.e. `$HOME/Gemfile`)? I'd like to understand what the use case is for this as I might need to detect and warn against this so people have a better initial experience.

> I assume the invalid gemspecs... since it would have to read my brain to fill in this info?

So Gemsmith tries to intelligently (or best it can) build out the `source_code_uri`, `homepage`, etc. based on system information (like your Git config) or whatever you have configured in your Gemsmith configuration (i.e. `~/.config/gemsmith/configuration.yml`). See the gem URL section of this [example configuration](https://github.com/bkuhlmann/gemsmith#configuration) for details.

If Gemsmith can't compute a proper URL, it'll do as best it can but might not be in a valid format. This is actually a good thing as Bundler will then warn that your gemspec is incomplete (see your `example/example.gemspec` URL settings for details). If you update that gemspec with valid URLs, those errors will go away.

**Comment by tleish** [comment]
The global Gemfile `$HOME/Gemfile` was a failed attempt to automate installing globally used gems (pry, iStats, rubocop, flay, etc).  When I move to a new machine I can run:
```
cd $HOME
gem install bundler
bundle install
```
It didn't work out the way I had hoped and I had to manually install each gem separately anyway, but I never removed the `$HOME/Gemfile`.

**Comment by bkuhlmann** [comment]
@tleish Ah, OK, that's helpful. By the way, I've solved that problem using Bash scripts. You might like my [Ruby Setup](https://github.com/bkuhlmann/ruby_setup) project as an example. Great for new or existing machine setup. Anyway, might give you ideas.
